[project]
name = "judit-langgraph-websearchagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Judit Mattes", email = "juditmattes5@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.4.0",
    "langchain-anthropic>=1.7.5",
    "langchain-tavily>=0.2.18",
]

[project.scripts]
judit-langgraph-websearchagent = "judit_langgraph_websearchagent:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
